window:
  padding:
    x: 5
    y: 5

  decorations: none

font:
  normal:
    family: JetBrainsMono Nerd Font

  bold:
    family: JetBrainsMono Nerd Font

  italic:
    family: JetBrainsMono Nerd Font

  bold_italic:
    family: JetBrainsMono Nerd Font

draw_bold_text_with_bright_colors: true

live_config_reload: true

# Uncomment to use zellij with FISH
shell:
  program: zellij
  args:
    - options
    - --default-shell
    - fish

# Uncomment to use zellij with NUSHELL
# shell:
#   program: zellij
#   args:
#     - options
#     - --default-shell
#     - nu
